# On PR toward `main`: run builds, run tests, and deploy to staging

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Integration Tests
        run: |
          echo TODO
          # npm ci
          # npm run build
          # npm run test:e2e
        env:
          CI: true
          NODE_ENV: test
          # DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          # CORDE_TEST_TOKEN: ${{ secrets.CORDE_TEST_TOKEN }}
          # CORDE_BOT_ID: ${{ secrets.CORDE_BOT_ID }}
          # BOT_TEST_ID: ${{ secrets.BOT_TEST_ID }}
          # GUILD_ID: ${{ secrets.GUILD_ID }}
          # CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
