# On PR toward `main`: run builds, run tests, and deploy to staging

when:
  - event: manual
  - event: pull_request
    branch: main

steps:
  test:
    name: Integration Tests
    image: node:18
    commands:
      - echo TODO
      # - npm ci
      # - npm run build
      # - npm run test:e2e
    environment:
      - CI=true
      - NODE_ENV=test
    # secrets:
    #   - discord_token
    #   - corde_test_token
    #   - corde_bot_id
    #   - bot_test_id
    #   - guild_id
    #   - channel_id
